---
title: "Advanced R and R Packages Workshop"
---

Welcome to the website for the Advanced R and R Packages Workshop.

This is a three-day workshop, taking place at The University of Warwick, June 19th-21st, 2023.

It is aimed primarily at graduate students in the Department of Statistics, but open to all interested members of the university, should space all. For more details on how to register, see the [join](join.qmd) page.

## Syllabus overview

The **Advanced R** sections of the workshop covers functions, classes and methods, efficient programming, profiling, C++ and Rcpp.

The **R Packages** sections of the workshop covers the entire process of creating a package, including data, checking and testing, all levels of documentation, publication and maintenance. The final session covers the advanced topic of using Rcpp code in a package.

For more details, see the [content](content.qmd) page.


## Session details

{{< fa calendar >}} &nbsp; June 19th-21st, 2023

{{< fa location-dot >}} &nbsp; Room OC1.02, The Oculus, University of Warwick

{{< fa utensils >}} &nbsp; Lunch provided each day

{{< fa calendar-alt >}} &nbsp; See the full [schedule](schedule.qmd).


## Instructor details

{{< fa user >}} &nbsp; [Ella Kaye](https://warwick.ac.uk/ellakaye) and [Heather Turner](https://warwick.ac.uk/heatherturner)

{{< fa envelope >}} &nbsp; [ella.m.kaye@warwick.ac.uk](mailto:ella.m.kaye@warwick.ac.uk) and [h.turner.1@warwick.ac.uk](mailto:h.turner.1@warwick.ac.uk)

## Prerequistes

Please see the [prerequisites](prerequisites.qmd) page for details on getting set up in advance of the workshop.
