---
title: Prerequisites
---

## Prior knowledge

This is an advanced R course, so basic knowledge of R is expected. 

The first three sessions of Warwick-Stats-Resources R Foundations course covers the required material:

- [Introduction to R and RStudio](https://warwick-stats-resources.github.io/R-training/content/01-foundations/01-intro.html)
- [Data Wrangling](https://warwick-stats-resources.github.io/R-training/content/01-foundations/02-data-wrangling.html)
- [Programming in R](https://warwick-stats-resources.github.io/R-training/content/01-foundations/03-programming.html)

Members of the University of Warwick can have access to video recordings of these sessions being taught online in Autumn Term 2022. Please contact [ella.m.kaye@warwick.ac.uk](mailto:ella.m.kaye@warwick.ac.uk) to be sent the links.

## git and GitHub

Although there will be some time dedicated to this in the workshop, it would be advantageous if you already have:

- `git` installed on your computer. See <https://git-scm.com/book/en/v2/Getting-Started-Installing-Git>
- a [GitHub](https://github.com) account
- a GitHub PAT configured to work with RStudio

The [git and GitHub](https://warwick-stats-resources.github.io/R-training/content/02-advanced/01-git.html) material from a previous version of this workshop walks through the setup.

## R and RStudio

Please ensure that you have up-to-date versions of R and RStudio installed prior to the first session. If you are on MacOS/Linux or a self-managed Windows laptop, install the latest versions, currently R-4.3.0 and RStudio-2023.03.1. 

We also **strongly** recommend all participants to install the development tools to avoid potential issues installing packages.

### ITS Managed Windows Machines

R and RStudio are available on student computers (via Start, All Programs) and also staff computers (via Start, All Programs, Software Center).

### Installing R

Download the pre-compiled binary for your OS from <https://cloud.r-project.org/> and install. More specifically:

**For Windows**

Click "Download R for Windows", then "base", then "Download R-4.3.0 for Windows". This will download an `.exe` file; once downloaded, open to start the installation. 

**For Mac**

Click "Download R for macOS", then "R-4.3.0-arm64.pkg" (the first option) to download the installer for Macs with **Apple Silicon** chips or "R-4.3.0-x86_64.pkg" (the second option) to download the installer for Macs with **Intel** chips. Run the installer to complete installation.

**For Linux**

Click "Download R for Linux". Instructions on installing are given for Debian, Fedora, Redhat, Suse and Ubuntu distributions. Where there is a choice, install both `r-base` and `r-base-dev`.

### Installing R Studio Desktop (Open Source Edition)

Downloads are available from <https://posit.co/download/rstudio-desktop/#download>

Download the relevant installer either under the "Install RStudio" header or, scrolling down the page, from the 'All installers and Tarballs' section. Run the installer to complete installation.
 
### Development Tools

Some additional tools may be required to compile R packages from source.

**For Windows**

NOTE: This does not require admin rights.

Download the Rtools installer that matches your version of R from 
<https://cran.r-project.org/bin/windows/Rtools/>. Run the installer, `Rtools.exe`, keeping the 
default settings.

**For Mac**

Install Command Line Tools. 

Either:

1.  Download and install XCode from the Mac AppStore: <http://itunes.apple.com/us/app/xcode/id497799835?mt=12>
2.  Within XCode go to Preferences -> Downloads and install the Command Line 
Tools

Or for a smaller download size:

1. Register as an Apple Developer (free) here: <https://developer.apple.com/programs/register/>
2. Download the Command Line Tools for XCode appropriate for the version of 
OS X you are running from here: <https://developer.apple.com/downloads/>

**For Linux**

If you installed `r-base-dev`, when installing R, you should have all you need 
to build packages from source. Otherwise return to the instructions for 
installing R for your distribution and follow the instructions there to install 
the additional tools.
